# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0010_auto_20170325_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mluser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
