# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0011_auto_20170325_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managerApp.MlUser'),
        ),
    ]
