# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0012_article_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mluser',
            name='access_token',
            field=models.CharField(max_length=999),
        ),
    ]
