# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0013_auto_20170326_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mluser',
            name='itemList',
            field=models.CharField(default=0, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mluser',
            name='userId',
            field=models.CharField(default=[], max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mluser',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
    ]
