# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0014_auto_20170326_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='itemId',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
