# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0015_article_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mluser',
            name='test_account',
            field=models.BooleanField(default=False),
        ),
    ]
