# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0016_mluser_test_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='APP_USR-4704790082736526-032620-7c743ad9f87cedac9f7bfeb331e632a6__L_G__-38184225', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='mluser',
            name='access_token',
        ),
    ]
