# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0018_auto_20170327_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='prueba', max_length=60),
        ),
    ]
