# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0019_auto_20170327_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='available_quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='buying_mode',
            field=models.CharField(default='buy_it_now', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='category_id',
            field=models.CharField(default='MLA3530', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='condition',
            field=models.CharField(default='new', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='currency_id',
            field=models.CharField(default='ARS', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='Item de test - No Ofertar', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article',
            name='listing_type_id',
            field=models.CharField(default='gold_special', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='pictures',
            field=models.URLField(default='[{"source":"http://mla-s2-p.mlstatic.com/968521-MLA20805195516_072016-O.jpg"}]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(default='10'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Item de test - No Ofertar', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='video_id',
            field=models.CharField(default='YOUTUBE_ID_HERE', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='warranty',
            field=models.CharField(default='12 months', max_length=60),
        ),
    ]
