# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0020_auto_20170327_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pictures',
            field=models.URLField(default='http://mla-s2-p.mlstatic.com/968521-MLA20805195516_072016-O.jpg', max_length=2000),
        ),
    ]
