# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0021_auto_20170327_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Electronica audio y video', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='permalink',
            field=models.URLField(default='http://mla-s2-p.mlstatic.com/968521-MLA20805195516_072016-O.jpg', max_length=2000),
        ),
    ]
