# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0024_auto_20170328_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Globals',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.URLField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
