# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0025_auto_20170413_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.URLField(default='active', max_length=50),
        ),
    ]
