# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0026_auto_20170413_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mluser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='mluser',
            name='itemList',
        ),
        migrations.RemoveField(
            model_name='mluser',
            name='password',
        ),
    ]
