# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0027_auto_20170414_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.CharField(default='No especificado', max_length=60),
        ),
    ]
