# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0022_auto_20170327_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
